# Settings for apt-related roles
---
apt_preferences:
  # don't install from testing unless specified
  testing:
    package: '*'
    pin: 'release a=testing'
    priority: '-10'
  # Install a newer version of trac
  testing-trac:
    package: 'trac'
    pin: 'release a=testing'
    priority: '900'

apt_sources:
  testing:
    repo: "deb {{ default_repo }} stretch main"
