# Settings for trac
---
trac:
  plugins:
    apt:
      - accountmanager
  instances:
    mediagoblin:
      path: '/var/trac/mediagoblin/'
      static_files: 'trac_static'
      config:
        trac:
          database: "mysql://trac:{{ mediagoblin_trac_mysql_password }}@localhost:3306/mediagoblin_trac"
        header_logo:
          alt: 'GNU MediaGoblin'
          height: '-1'
          link: 'https://issues.mediagoblin.org/report/3'
          src: 'site/mediagoblin_bugs.png'
          width: '-1'
        project:
          descr: 'GNU MediaGoblin'
          footer: '<a href="http://mediagoblin.org/">GNU MediaGoblin</a> issue tracker'
          name: 'GNU MediaGoblin'
          url: 'https://issues.mediagoblin.org/'
          file: 'static/mediagoblin_bugs.png'
        account-manager:
          account_changes_notify_addresses: 'tracaccount@tenthcircle.net'
          force_passwd_change: 'true'
          hash_method: 'HtDigestHashMethod'
          notify_actions: 'new,change,delete'
          password_store: 'SessionStore'
          persistent_sessions: 'true'
          refresh_passwd: 'False'
          register_check: 'BasicCheck, BotTrapCheck, EmailCheck, RegistrationFilterAdapter'
          user_lock_max_time: '86400'
          verify_email: 'true'
        components:
          Acct_mgr.admin.*: 'enabled'
          acct_mgr.api.*: 'enabled'
          acct_mgr.db.*: 'enabled'
          acct_mgr.db.sessionstore: 'enabled'
          acct_mgr.htfile.*: 'enabled'
          acct_mgr.htfile.htdigeststore: 'disabled'
          acct_mgr.htfile.htpasswdstore: 'disabled'
          acct_mgr.http.*: 'enabled'
          acct_mgr.http.httpauthstore: 'disabled'
          acct_mgr.notification.*: 'enabled'
          acct_mgr.notification.accountchangelistener: 'enabled'
          acct_mgr.pwhash.*: 'enabled'
          acct_mgr.pwhash.htdigesthashmethod: 'enabled'
          acct_mgr.pwhash.htpasswdhashmethod: 'disabled'
          acct_mgr.register.basiccheck: 'enabled'
          acct_mgr.register.bottrapcheck: 'enabled'
          acct_mgr.register.emailcheck: 'enabled'
          acct_mgr.register.emailverificationmodule: 'enabled'
          acct_mgr.register.registrationmodule: 'enabled'
          acct_mgr.svnserve.*: 'enabled'
          acct_mgr.svnserve.svnservepasswordstore: 'disabled'
          acct_mgr.web_ui.*: 'enabled'
          acct_mgr.web_ui.registrationmodule: 'disabled'
          dynfields.*: 'enabled'
          trac.web.auth.loginmodule: 'disabled'
          tracopt.ticket.deleter: 'enabled'
          tracopt.ticket.deleter.ticketdeleter: 'enabled'
          tracopt.versioncontrol.svn.svn_fs.subversionconnector: 'disabled'
          tracopt.versioncontrol.svn.svn_prop.subversionmergepropertydiffrenderer: 'disabled'
          tracopt.versioncontrol.svn.svn_prop.subversionmergepropertyrenderer: 'disabled'
          tracopt.versioncontrol.svn.svn_prop.subversionpropertyrenderer: 'disabled'
          tracspamfilter.*: 'enabled'
          tracsubtickets.api.*: 'enabled'
          tracsubtickets.web_ui.*: 'enabled'
        notifications:
          smtp_always_cc: 'cwebber@dustycloud.org'
          smtp_default_domain: 'mediagoblin.org'
          smtp_enabled: 'true'
          smtp_from: 'trac@mediagoblin.org'
          smtp_replyto: 'trac@mediagoblin.org'
          spam_filter: ''
          account_karma: '0'
          akismet_api_key: ''
          akismet_api_url: 'rest.akismet.com/1.1/'
          akismet_karma: '10'
          attachment_karma: '0'
          authenticated_karma: '10'
          bayes_karma: '0'
          blogspam_json_api_url: 'test.blogspam.net:9999'
          blogspam_json_skip_tests: '45-wordcount.js,60-drone.js,80-sfs.js'
          blogspam_karma: '5'
          botscout_api_key: ''
          botscout_karma: '3'
          captcha: 'ImageCaptcha'
          captcha_areyouahuman_publisher_key: ''
          captcha_areyouahuman_scoring_key: ''
          captcha_expression_ceiling: '10'
          captcha_expression_terms: '3'
          captcha_failed_karma: '1'
          captcha_image_alphabet: 'abcdefghkmnopqrstuvwxyz'
          captcha_image_font_size: '25'
          captcha_image_fonts: 'vera.ttf'
          captcha_image_letters: '6'
          captcha_karma: '15'
          captcha_karma_lifetime: '86400'
          captcha_keycaptcha_private_key: ''
          captcha_keycaptcha_user_id: ''
          captcha_recaptcha_private_key: ''
          captcha_recaptcha_public_key: ''
          extlinks_karma: '2'
          fspamlist_api_key: ''
          fspamlist_karma: '3'
          ip_throttle_karma: '3'
          ipregex_karma: '20'
          is_forwarded: 'true'
          logging_enabled: 'true'
          min_karma: '0'
          purge_age: '7'
          regex_karma: '5'
          register_karma: '0'
          reject_handler: 'CaptchaSystem'
          session_karma: '9'
          skip_external: '20'
          skip_externalham: '30'
          spam_monitor_entries: '100'
          stop_external: '50'
          stop_externalham: '50'
          stopforumspam_api_key: ''
          stopforumspam_karma: '4'
          train_external: 'true'
          trap_karma: '25'
          trust_authenticated: 'false'
          use_external: 'true'
